databases:
  - name: gym_austral_back
    databaseName: gym_austral_back
    user: gym_austral_back

services:
  - type: web
    name: gym_austral_back
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym_austral_back
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4