# Generated by Django 4.0.6 on 2022-07-17 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_day', models.IntegerField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routine')),
            ],
        ),
    ]
