# Generated by Django 4.0.6 on 2022-07-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_muscle_group'),
        ('routine_day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineday',
            name='exercises',
            field=models.ManyToManyField(to='exercise.exercise'),
        ),
    ]
