# Generated by Django 4.0.6 on 2022-07-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0002_alter_exercise_muscle_group'),
        ('routine_day', '0003_remove_routineday_exercises_alter_routineday_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routine_day.routineday')),
            ],
        ),
    ]
